// src/components/auth/recovery/TwoFactorRecovery.tsx
import { useState } from 'react';

const DUMMY_RECOVERY_CODES = ['AAAA-BBBB-CCCC', 'DDDD-EEEE-FFFF'];

interface Props {
  level: 'normal' | 'admin';
  onSuccess: () => void;
  onBack: () => void;
}

export function TwoFactorRecovery({ level, onSuccess, onBack }: Props) {
  const [step, setStep] = useState<'verify' | 'recovery' | 'done'>('verify');
  const [email, setEmail] = useState('');
  const [code, setCode] = useState('');
  const [recoveryCode, setRecoveryCode] = useState('');
  const [error, setError] = useState('');

  function handleVerify(e: React.SubmitEvent<HTMLFormElement>) {
    e.preventDefault();
    if (!email.trim()) {
      setError('请输入邮箱');
      return;
    }
    if (code !== '000000') {
      setError('验证码错误（模拟码：000000）');
      return;
    }
    setError('');
    setStep('recovery');
  }

  function handleRecovery(e: React.SubmitEvent<HTMLFormElement>) {
    e.preventDefault();
    if (DUMMY_RECOVERY_CODES.some((c) => c === recoveryCode.toUpperCase().trim())) {
      setStep('done');
    } else {
      setError('恢复码无效');
    }
  }

  return (
    <div className="rounded-2xl bg-base-100 shadow-2xl border border-base-300 p-6 sm:p-8">
      <h2 className="text-xl font-semibold text-center mb-4">2FA 恢复</h2>

      {step === 'verify' && (
        <form onSubmit={handleVerify} className="space-y-4">
          <p className="text-sm text-neutral text-center">请通过邮箱验证身份</p>
          <div>
            <label className="label pb-1">
              <span className="label-text font-medium">邮箱</span>
            </label>
            <input
              type="email"
              className="input input-bordered w-full"
              value={email}
              onInput={(e) => setEmail(e.currentTarget.value)}
              placeholder="请输入绑定邮箱"
            />
          </div>
          <div>
            <label className="label pb-1">
              <span className="label-text font-medium">验证码</span>
            </label>
            <input
              type="text"
              className="input input-bordered w-full"
              value={code}
              onInput={(e) => setCode(e.currentTarget.value)}
              placeholder="输入验证码（模拟：000000）"
              maxLength={6}
            />
          </div>
          <p className="text-xs text-success text-center">模拟验证码：000000</p>
          {error && <div className="alert alert-error text-sm">{error}</div>}
          <button type="submit" className="btn btn-primary w-full">
            验证
          </button>
          <button type="button" className="btn btn-ghost w-full btn-sm" onClick={onBack}>
            返回
          </button>
        </form>
      )}

      {step === 'recovery' && (
        <form onSubmit={handleRecovery} className="space-y-4">
          <p className="text-sm text-neutral text-center">请输入备用恢复码</p>
          <div>
            <label className="label pb-1">
              <span className="label-text font-medium">恢复码</span>
            </label>
            <input
              type="text"
              className="input input-bordered w-full"
              value={recoveryCode}
              onInput={(e) => setRecoveryCode(e.currentTarget.value)}
              placeholder="格式：AAAA-BBBB-CCCC"
            />
          </div>
          {error && <div className="alert alert-error text-sm">{error}</div>}
          <button type="submit" className="btn btn-primary w-full">
            验证
          </button>
          {level === 'admin' && (
            <button type="button" className="btn btn-ghost w-full btn-sm" onClick={() => onSuccess()}>
              联系其他管理员协助（模拟）
            </button>
          )}
        </form>
      )}

      {step === 'done' && (
        <div className="text-center space-y-4">
          <div className="text-5xl">✅</div>
          <p className="font-semibold">恢复成功</p>
          <p className="text-sm text-neutral">请重新设置 2FA</p>
          <button type="button" className="btn btn-primary btn-sm" onClick={onSuccess}>
            完成
          </button>
        </div>
      )}
    </div>
  );
}

// src/features/auth/components/recovery/TwoFactorRecovery.vue
<template>
  <div
    class="rounded-2xl bg-card-bg shadow-2xl border border-surface-3 p-6 sm:p-8"
  >
    <h2 class="text-xl font-semibold text-center mb-4">
      {{ t("auth.twoFactor.recoveryTitle") }}
    </h2>

    <!-- Verify email -->
    <form
      v-if="step === 'verify'"
      @submit.prevent="handleVerify"
      class="space-y-4"
    >
      <p class="text-sm text-text-muted text-center">
        {{ t("auth.twoFactor.verifyIdentity") }}
      </p>
      <div>
        <label class="label pb-1"
          ><span class="label-text font-medium">{{
            t("auth.twoFactor.email")
          }}</span></label
        >
        <input
          type="email"
          class="input input-bordered w-full"
          v-model="email"
          :placeholder="t('auth.twoFactor.enterBoundEmail')"
        />
      </div>
      <div>
        <label class="label pb-1"
          ><span class="label-text font-medium">{{
            t("auth.twoFactor.code")
          }}</span></label
        >
        <input
          type="text"
          class="input input-bordered w-full"
          v-model="code"
          :placeholder="t('auth.twoFactor.enter6Digit')"
          maxlength="6"
        />
      </div>
      <div v-if="error" class="alert alert-error text-sm">{{ error }}</div>
      <button
        type="submit"
        class="btn btn-primary w-full"
        :disabled="submitting"
      >
        {{ t("auth.twoFactor.verify") }}
      </button>
      <button
        type="button"
        class="btn btn-ghost w-full btn-sm"
        @click="emit('back')"
      >
        {{ t("common.back") }}
      </button>
    </form>

    <!-- Recovery code -->
    <form
      v-else-if="step === 'recovery'"
      @submit.prevent="handleRecovery"
      class="space-y-4"
    >
      <p class="text-sm text-text-muted text-center">
        {{ t("auth.twoFactor.enterRecoveryTitle") }}
      </p>
      <div>
        <label class="label pb-1"
          ><span class="label-text font-medium">{{
            t("auth.twoFactor.recoveryCodeName")
          }}</span></label
        >
        <input
          type="text"
          class="input input-bordered w-full"
          v-model="recoveryCode"
          :placeholder="t('auth.twoFactor.recoveryCodePlaceholder')"
        />
      </div>
      <div v-if="error" class="alert alert-error text-sm">{{ error }}</div>
      <button
        type="submit"
        class="btn btn-primary w-full"
        :disabled="submitting"
      >
        {{ t("auth.twoFactor.verify") }}
      </button>
      <!-- 管理员级别不得绕过校验：这里只做提示，绝不 emit success（是否放行由上游权限决定） -->
      <p
        v-if="props.level === 'admin'"
        class="text-xs text-text-muted text-center"
      >
        {{ t("auth.twoFactor.contactAdmin") }}
      </p>
    </form>

    <!-- Done -->
    <div v-else-if="step === 'done'" class="text-center space-y-4">
      <div class="flex justify-center">
        <svg
          class="w-14 h-14 text-success"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
          <polyline points="22 4 12 14.01 9 11.01" />
        </svg>
      </div>
      <p class="font-semibold">{{ t("auth.twoFactor.recoverySuccess2") }}</p>
      <p class="text-sm text-text-muted">
        {{ t("auth.twoFactor.pleaseReSetup2fa") }}
      </p>
      <button
        type="button"
        class="btn btn-primary btn-sm"
        @click="emit('success')"
      >
        {{ t("auth.twoFactor.done") }}
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { authApi } from "~/lib/api/modules/auth";
import { t } from "~/lib/i18n";

const emit = defineEmits<{
  (e: "success"): void;
  (e: "back"): void;
}>();

const props = withDefaults(
  defineProps<{
    level: "normal" | "admin";
    /** 登录/强制 2FA 流程下发的临时令牌；身份与恢复码校验一律在后端完成 */
    tempToken?: string;
  }>(),
  { tempToken: "" },
);

const step = ref<"verify" | "recovery" | "done">("verify");
const email = ref("");
const code = ref("");
const recoveryCode = ref("");
const error = ref("");
const submitting = ref(false);

async function handleVerify() {
  error.value = "";
  if (!email.value.trim()) {
    error.value = t("auth.twoFactor.enterEmailError");
    return;
  }
  const value = code.value.trim();
  if (!/^\d{6}$/.test(value)) {
    error.value = t("auth.twoFactor.enter6DigitError");
    return;
  }
  if (!props.tempToken) {
    error.value = t("messages.auth.missingTempToken");
    return;
  }
  submitting.value = true;
  try {
    // 身份校验交给后端：客户端不再持有任何「正确答案」字面量
    const r = await authApi.verify2FA(props.tempToken, value);
    if (r.isErr()) {
      error.value = r.error.message;
      return;
    }
    step.value = "recovery";
  } finally {
    submitting.value = false;
  }
}

async function handleRecovery() {
  error.value = "";
  const value = recoveryCode.value.trim();
  if (!value) {
    error.value = t("auth.twoFactor.enterRecoveryCode");
    return;
  }
  if (!props.tempToken) {
    error.value = t("messages.auth.missingTempToken");
    return;
  }
  submitting.value = true;
  try {
    // 恢复码由后端与用户已存储的（哈希）恢复码比对，客户端不再内置任何有效恢复码
    const r = await authApi.verify2FA(props.tempToken, null, value);
    if (r.isErr()) {
      error.value = r.error.message;
      return;
    }
    step.value = "done";
  } finally {
    submitting.value = false;
  }
}
</script>
