// src/components/auth/settings/BindMethods.tsx
import { useState } from 'react';
import type { DemoUser } from '~/types/auth';

interface Props {
  user: DemoUser;
  onUpdate: (user: DemoUser) => void;
}

export function BindMethods({ user, onUpdate }: Props) {
  const [showBind, setShowBind] = useState<string | null>(null);
  const [input, setInput] = useState('');
  const [code, setCode] = useState('');
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  function handleBind(method: string) {
    setShowBind(method);
    setInput('');
    setCode('');
    setError('');
    setSuccess('');
  }

  function handleVerify() {
    if (!input.trim()) {
      setError(`请输入${showBind === 'phone' ? '手机号' : '邮箱'}`);
      return;
    }
    if (code !== '000000') {
      setError('验证码错误（模拟码：000000）');
      return;
    }

    const updated: DemoUser = { ...user };
    if (showBind === 'email') {
      updated.email = input.trim();
      if (!updated.bindings.includes('email')) updated.bindings.push('email');
    } else if (showBind === 'phone') {
      updated.phone = input.trim();
      if (!updated.bindings.includes('phone')) updated.bindings.push('phone');
    } else if (showBind === 'github') {
      updated.hasGithub = true;
      if (!updated.bindings.includes('github')) updated.bindings.push('github');
    } else if (showBind === 'passkey') {
      updated.hasPasskey = true;
      if (!updated.bindings.includes('passkey')) updated.bindings.push('passkey');
    }

    // local → normal 自动升级
    if (
      user.level === 'local' &&
      showBind &&
      (showBind === 'email' || showBind === 'phone' || showBind === 'github' || showBind === 'passkey')
    ) {
      updated.level = 'normal';
      setSuccess(
        `${showBind === 'email' ? '邮箱' : showBind === 'phone' ? '手机号' : showBind === 'github' ? 'Github' : 'Passkey'} 绑定成功！账户已从本地账户升级为普通账户，刷新后生效。`
      );
    } else {
      setSuccess('绑定成功');
    }
    onUpdate(updated);
    setShowBind(null);
  }

  function handleUnbind(method: string) {
    const updated: DemoUser = { ...user };
    if (method === 'email') {
      updated.email = null;
      updated.bindings = updated.bindings.filter((b) => b !== 'email');
    }
    if (method === 'phone') {
      updated.phone = null;
      updated.bindings = updated.bindings.filter((b) => b !== 'phone');
    }
    if (method === 'github') {
      updated.hasGithub = false;
      updated.bindings = updated.bindings.filter((b) => b !== 'github');
    }
    if (method === 'passkey') {
      updated.hasPasskey = false;
      updated.bindings = updated.bindings.filter((b) => b !== 'passkey');
    }
    onUpdate(updated);
    setSuccess('解绑成功');
  }

  return (
    <div className="space-y-4">
      <h3 className="text-lg font-semibold">登录方式管理</h3>
      {success && <div className="alert alert-success text-sm">{success}</div>}

      {(['email', 'phone', 'github', 'passkey'] as const).map((method) => (
        <div key={method} className="flex items-center justify-between p-3 bg-base-200 rounded-lg">
          <div>
            <span className="font-medium">
              {method === 'email'
                ? '邮箱'
                : method === 'phone'
                  ? '手机号'
                  : method === 'github'
                    ? 'Github OAuth'
                    : 'Passkey 通行密钥'}
            </span>
            <span className="text-xs text-neutral ml-2">
              {method === 'email' && user.email ? user.email : method === 'phone' && user.phone ? user.phone : ''}
            </span>
            <span className={`badge badge-xs ml-2 ${user.bindings.includes(method) ? 'badge-success' : 'badge-ghost'}`}>
              {user.bindings.includes(method) ? '已绑定' : '未绑定'}
            </span>
          </div>
          <div className="flex gap-1">
            {user.bindings.includes(method) ? (
              <button type="button" className="btn btn-ghost btn-xs text-error" onClick={() => handleUnbind(method)}>
                解绑
              </button>
            ) : (
              <button
                type="button"
                className="btn btn-ghost btn-xs"
                onClick={() => handleBind(method)}
                disabled={user.level === 'local' && method === 'passkey'}
              >
                绑定
              </button>
            )}
          </div>
        </div>
      ))}

      {showBind && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
          onClick={() => setShowBind(null)}
        >
          <div
            className="bg-base-100 rounded-2xl shadow-2xl p-6 w-full max-w-sm mx-4"
            onClick={(e) => e.stopPropagation()}
          >
            <h4 className="font-semibold mb-4">
              绑定{' '}
              {showBind === 'email'
                ? '邮箱'
                : showBind === 'phone'
                  ? '手机号'
                  : showBind === 'github'
                    ? 'Github'
                    : 'Passkey'}
            </h4>
            {showBind === 'github' ? (
              <div className="space-y-4 text-center">
                <p className="text-sm text-neutral">模拟 Github OAuth 授权绑定</p>
                <button type="button" className="btn btn-primary btn-sm" onClick={handleVerify}>
                  模拟授权并绑定
                </button>
              </div>
            ) : showBind === 'passkey' ? (
              <div className="space-y-4 text-center">
                <p className="text-sm text-neutral">模拟 Passkey 创建</p>
                <button type="button" className="btn btn-primary btn-sm" onClick={handleVerify}>
                  模拟创建通行密钥
                </button>
              </div>
            ) : (
              <div className="space-y-3">
                <div>
                  <label className="label pb-1">
                    <span className="label-text">{showBind === 'phone' ? '手机号' : '邮箱'}</span>
                  </label>
                  <input
                    type="text"
                    className="input input-bordered w-full"
                    value={input}
                    onInput={(e) => setInput(e.currentTarget.value)}
                  />
                </div>
                <div>
                  <label className="label pb-1">
                    <span className="label-text">验证码</span>
                  </label>
                  <input
                    type="text"
                    className="input input-bordered w-full"
                    value={code}
                    onInput={(e) => setCode(e.currentTarget.value)}
                    placeholder="模拟码：000000"
                    maxLength={6}
                  />
                </div>
                {error && <div className="text-error text-xs">{error}</div>}
                <button type="button" className="btn btn-primary btn-sm w-full" onClick={handleVerify}>
                  验证并绑定
                </button>
              </div>
            )}
            <button type="button" className="btn btn-ghost btn-xs w-full mt-2" onClick={() => setShowBind(null)}>
              取消
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

// src/components/auth/settings/BindMethods.vue
<template>
  <div class="space-y-4">
    <h3 class="text-lg font-semibold">登录方式管理</h3>
    <div v-if="successMsg" class="alert alert-success text-sm">{{ successMsg }}</div>

    <div
      v-for="method in methods"
      :key="method.key"
      class="flex items-center justify-between p-3 bg-base-200 rounded-lg"
    >
      <div>
        <span class="font-medium">{{ method.label }}</span>
        <span class="text-xs text-neutral ml-2">{{ method.detail }}</span>
        <span class="badge badge-xs ml-2" :class="user.bindings.includes(method.key) ? 'badge-success' : 'badge-ghost'">
          {{ user.bindings.includes(method.key) ? '已绑定' : '未绑定' }}
        </span>
      </div>
      <div class="flex gap-1">
        <button
          v-if="user.bindings.includes(method.key)"
          type="button"
          class="btn btn-ghost btn-xs text-error"
          @click="handleUnbind(method.key)"
        >
          解绑
        </button>
        <button
          v-else
          type="button"
          class="btn btn-ghost btn-xs"
          @click="handleBind(method.key)"
          :disabled="user.level === 'local' && method.key === 'passkey'"
        >
          绑定
        </button>
      </div>
    </div>

    <!-- Bind modal -->
    <div
      v-if="showBind"
      class="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
      @click="showBind = null"
    >
      <div class="bg-base-100 rounded-2xl shadow-2xl p-6 w-full max-w-sm mx-4" @click.stop>
        <h4 class="font-semibold mb-4">绑定 {{ bindLabel }}</h4>

        <div v-if="showBind === 'github'" class="space-y-4 text-center">
          <p class="text-sm text-neutral">模拟 Github OAuth 授权绑定</p>
          <button type="button" class="btn btn-primary btn-sm" @click="handleVerify">模拟授权并绑定</button>
        </div>

        <div v-else-if="showBind === 'passkey'" class="space-y-4 text-center">
          <p class="text-sm text-neutral">模拟 Passkey 创建</p>
          <button type="button" class="btn btn-primary btn-sm" @click="handleVerify">模拟创建通行密钥</button>
        </div>

        <div v-else class="space-y-3">
          <div>
            <label class="label pb-1"
              ><span class="label-text">{{ showBind === 'phone' ? '手机号' : '邮箱' }}</span></label
            >
            <input type="text" class="input input-bordered w-full" v-model="bindInput" />
          </div>
          <div>
            <label class="label pb-1"><span class="label-text">验证码</span></label>
            <input
              type="text"
              class="input input-bordered w-full"
              v-model="bindCode"
              placeholder="模拟码：000000"
              maxlength="6"
            />
          </div>
          <div v-if="error" class="text-error text-xs">{{ error }}</div>
          <button type="button" class="btn btn-primary btn-sm w-full" @click="handleVerify">验证并绑定</button>
        </div>

        <button type="button" class="btn btn-ghost btn-xs w-full mt-2" @click="showBind = null">取消</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import type { DemoUser } from '~/types/auth';

const props = defineProps<{
  user: DemoUser;
  onUpdate: (user: DemoUser) => void;
}>();

const methods = computed(() => [
  { key: 'email' as const, label: '邮箱', detail: props.user.email || '' },
  { key: 'phone' as const, label: '手机号', detail: props.user.phone || '' },
  { key: 'github' as const, label: 'Github OAuth', detail: '' },
  { key: 'passkey' as const, label: 'Passkey 通行密钥', detail: '' },
]);

const showBind = ref<string | null>(null);
const bindInput = ref('');
const bindCode = ref('');
const error = ref('');
const successMsg = ref('');

const bindLabel = computed(() => {
  const map: Record<string, string> = { email: '邮箱', phone: '手机号', github: 'Github', passkey: 'Passkey' };
  return map[showBind.value || ''] || '';
});

function handleBind(method: string) {
  showBind.value = method;
  bindInput.value = '';
  bindCode.value = '';
  error.value = '';
  successMsg.value = '';
}

function handleVerify() {
  if (showBind.value === 'email' || showBind.value === 'phone') {
    if (!bindInput.value.trim()) {
      error.value = `请输入${showBind.value === 'phone' ? '手机号' : '邮箱'}`;
      return;
    }
    if (bindCode.value !== '000000') {
      error.value = '验证码错误（模拟码：000000）';
      return;
    }
  }

  const updated: DemoUser = { ...props.user };
  if (showBind.value === 'email') {
    updated.email = bindInput.value.trim();
    if (!updated.bindings.includes('email')) updated.bindings.push('email');
  } else if (showBind.value === 'phone') {
    updated.phone = bindInput.value.trim();
    if (!updated.bindings.includes('phone')) updated.bindings.push('phone');
  } else if (showBind.value === 'github') {
    updated.hasGithub = true;
    if (!updated.bindings.includes('github')) updated.bindings.push('github');
  } else if (showBind.value === 'passkey') {
    updated.hasPasskey = true;
    if (!updated.bindings.includes('passkey')) updated.bindings.push('passkey');
  }

  if (
    props.user.level === 'local' &&
    showBind.value &&
    ['email', 'phone', 'github', 'passkey'].includes(showBind.value)
  ) {
    updated.level = 'normal';
    successMsg.value = `${bindLabel.value} 绑定成功！账户已从本地账户升级为普通账户，刷新后生效。`;
  } else {
    successMsg.value = '绑定成功';
  }
  props.onUpdate(updated);
  showBind.value = null;
}

function handleUnbind(method: string) {
  const updated: DemoUser = { ...props.user };
  if (method === 'email') {
    updated.email = null;
    updated.bindings = updated.bindings.filter((b) => b !== 'email');
  }
  if (method === 'phone') {
    updated.phone = null;
    updated.bindings = updated.bindings.filter((b) => b !== 'phone');
  }
  if (method === 'github') {
    updated.hasGithub = false;
    updated.bindings = updated.bindings.filter((b) => b !== 'github');
  }
  if (method === 'passkey') {
    updated.hasPasskey = false;
    updated.bindings = updated.bindings.filter((b) => b !== 'passkey');
  }
  props.onUpdate(updated);
  successMsg.value = '解绑成功';
}
</script>
