// src/features/auth/components/login/MagicLinkLogin.vue
<template>
  <div class="space-y-4">
    <!-- Sent state -->
    <div v-if="stage === 'sent'" class="text-center space-y-4">
      <div class="rounded-xl border border-surface-3 bg-page-bg p-6 space-y-4">
        <div class="text-4xl">📧</div>
        <p class="font-semibold text-deep-text">
          {{ t("auth.login.magicSentTitle") }}
        </p>
        <p class="text-sm text-text-muted">
          {{ t("auth.login.magicSentSimulation") }}
          <span class="font-semibold">{{ email }}</span>
        </p>
        <div class="flex flex-col gap-2">
          <button
            type="button"
            class="btn btn-primary btn-sm"
            @click="handleSimulateClick"
            :disabled="loading"
          >
            <span
              v-if="loading"
              class="loading loading-spinner loading-xs"
            ></span>
            <template v-else>{{ t("auth.login.simulateClick") }}</template>
          </button>
          <div class="flex gap-2 justify-center">
            <button
              type="button"
              class="btn btn-ghost btn-xs"
              @click="goToStage('expired')"
            >
              {{ t("auth.login.simulateExpired") }}
            </button>
            <button
              type="button"
              class="btn btn-ghost btn-xs"
              @click="goToStage('used')"
            >
              {{ t("auth.login.simulateUsed") }}
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Expired state -->
    <div v-else-if="stage === 'expired'" class="text-center space-y-4">
      <div class="alert alert-warning">
        <span>{{ t("auth.login.linkExpired") }}</span>
      </div>
      <button
        type="button"
        class="btn btn-ghost btn-sm"
        @click="stage = 'input'"
      >
        {{ t("auth.login.backToResend") }}
      </button>
    </div>

    <!-- Used state -->
    <div v-else-if="stage === 'used'" class="text-center space-y-4">
      <div class="alert alert-warning">
        <span>{{ t("auth.login.linkUsed") }}</span>
      </div>
      <button
        type="button"
        class="btn btn-ghost btn-sm"
        @click="stage = 'input'"
      >
        {{ t("auth.login.backToResend") }}
      </button>
    </div>

    <!-- Input state (default) -->
    <form v-else @submit.prevent="handleSend" class="space-y-4">
      <p class="text-sm text-text-muted text-center">
        {{ t("auth.login.magicSendTo") }}
        <span class="font-semibold">{{ email }}</span>
      </p>
      <button type="submit" class="btn btn-primary w-full">
        {{ t("auth.login.sendMagicLink") }}
      </button>
    </form>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import { t } from "~/lib/i18n";
import type { LoginMethod } from "~/types/auth";

const emit = defineEmits<{
  (e: "login", method: LoginMethod, credentials: Record<string, string>): void;
}>();

const props = defineProps<{
  identifiedAccount: { email: string };
}>();

type Stage = "input" | "sent" | "expired" | "used";

const email = computed(() => props.identifiedAccount.email || "");
const stage = ref<Stage>("input");
const loading = ref(false);

function handleSend(e: Event) {
  e.preventDefault();
  stage.value = "sent";
}

// 模拟按钮的显式状态迁移：模板里裸改 stage 会把状态机写进视图、还能绕过在途请求，
// 收口到这里后将来要加冷却/重试上限/清错都有唯一落点
function goToStage(next: Stage) {
  loading.value = false;
  stage.value = next;
}

async function handleSimulateClick() {
  loading.value = true;
  emit("login", "magic-link", { email: email.value });
  loading.value = false;
}
</script>

// src/components/auth/login/MagicLinkLogin.tsx
import { useState } from 'react';
import type { LoginMethod, DemoUser } from '~/types/auth';

interface Props {
  onLogin: (method: LoginMethod, credentials: Record<string, string>) => Promise<void>;
  identifiedAccount: DemoUser;
}

type Stage = 'input' | 'sent' | 'expired' | 'used';

export function MagicLinkLogin({ onLogin, identifiedAccount }: Props) {
  const email = identifiedAccount.email || '';
  const [stage, setStage] = useState<Stage>('input');
  const [loading, setLoading] = useState(false);

  function handleSend(e: React.SubmitEvent<HTMLFormElement>) {
    e.preventDefault();
    setStage('sent');
  }

  async function handleSimulateClick() {
    setLoading(true);
    await onLogin('magic-link', { email });
    setLoading(false);
  }

  if (stage === 'sent') {
    return (
      <div className="space-y-4 text-center">
        <div className="rounded-xl border border-base-300 bg-base-200 p-6 space-y-4">
          <div className="text-4xl">📧</div>
          <p className="font-semibold text-base-content">魔法链接已发送</p>
          <p className="text-sm text-neutral">
            模拟已向 <span className="font-semibold">{email}</span> 发送登录链接
          </p>
          <div className="flex flex-col gap-2">
            <button type="button" className="btn btn-primary btn-sm" onClick={handleSimulateClick} disabled={loading}>
              {loading ? <span className="loading loading-spinner loading-xs"></span> : '模拟点击邮件链接'}
            </button>
            <div className="flex gap-2 justify-center">
              <button type="button" className="btn btn-ghost btn-xs" onClick={() => setStage('expired')}>
                模拟链接已过期
              </button>
              <button type="button" className="btn btn-ghost btn-xs" onClick={() => setStage('used')}>
                模拟链接已使用
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (stage === 'expired') {
    return (
      <div className="space-y-4 text-center">
        <div className="alert alert-warning">
          <span>链接已过期，请重新获取</span>
        </div>
        <button type="button" className="btn btn-ghost btn-sm" onClick={() => setStage('input')}>
          返回重新发送
        </button>
      </div>
    );
  }

  if (stage === 'used') {
    return (
      <div className="space-y-4 text-center">
        <div className="alert alert-warning">
          <span>链接已失效（已使用），请重新获取</span>
        </div>
        <button type="button" className="btn btn-ghost btn-sm" onClick={() => setStage('input')}>
          返回重新发送
        </button>
      </div>
    );
  }

  return (
    <form onSubmit={handleSend} className="space-y-4">
      <p className="text-sm text-neutral text-center">
        我们将向 <span className="font-semibold">{email}</span> 发送包含登录链接的邮件
      </p>
      <button type="submit" className="btn btn-primary w-full">
        发送魔法链接
      </button>
    </form>
  );
}
