// src/components/auth/login/PasswordLogin.tsx
import { useState } from 'react';
import { getAuthPath } from '../auth-paths';
import type { LoginMethod, DemoUser } from '~/types/auth';

interface Props {
  onLogin: (method: LoginMethod, credentials: Record<string, string>) => Promise<void>;
  identifiedAccount: DemoUser;
}

export function PasswordLogin({ onLogin, identifiedAccount }: Props) {
  const [password, setPassword] = useState('');
  const [passwordError, setPasswordError] = useState('');
  const [loading, setLoading] = useState(false);

  async function handleSubmit(e: React.SubmitEvent<HTMLFormElement>) {
    e.preventDefault();
    if (!password) {
      setPasswordError('请输入密码');
      return;
    }
    if (password.length < 6) {
      setPasswordError('密码长度不能少于 6 位');
      return;
    }
    setPasswordError('');
    setLoading(true);
    await onLogin('password', { username: identifiedAccount.username, password });
    setLoading(false);
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div>
        <label className="label pb-1" htmlFor="login-password">
          <span className="label-text font-medium">密码</span>
        </label>
        <input
          id="login-password"
          type="password"
          className={`input input-bordered w-full ${passwordError ? 'input-error' : ''}`}
          value={password}
          onInput={(e) => {
            setPassword(e.currentTarget.value);
            setPasswordError('');
          }}
          placeholder="请输入密码"
          autoComplete="current-password"
        />
        {passwordError && <span className="label-text-alt text-error">{passwordError}</span>}
      </div>
      {identifiedAccount.level !== 'local' && (
        <div className="text-right">
          <a href={getAuthPath('account/recovery')} className="text-xs text-primary hover:underline">
            忘记密码？
          </a>
        </div>
      )}
      <button type="submit" className="btn btn-primary w-full" disabled={loading}>
        {loading ? <span className="loading loading-spinner loading-xs"></span> : '登录'}
      </button>
    </form>
  );
}

// src/components/auth/login/PasswordLogin.vue
<template>
  <form @submit.prevent="handleSubmit" class="space-y-4">
    <div>
      <label class="label pb-1" for="login-password">
        <span class="label-text font-medium">密码</span>
      </label>
      <input
        id="login-password"
        type="password"
        class="input input-bordered w-full"
        :class="{ 'input-error': passwordError }"
        v-model="password"
        placeholder="请输入密码"
        autocomplete="current-password"
        @input="passwordError = ''"
      />
      <span v-if="passwordError" class="label-text-alt text-error">{{ passwordError }}</span>
    </div>
    <div v-if="identifiedAccount.level !== 'local'" class="text-right">
      <a :href="getAuthPath('account/recovery')" class="text-xs text-primary hover:underline">忘记密码？</a>
    </div>
    <button type="submit" class="btn btn-primary w-full" :disabled="loading">
      <span v-if="loading" class="loading loading-spinner loading-xs"></span>
      <template v-else>登录</template>
    </button>
  </form>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { getAuthPath } from '../auth-paths';
import type { LoginMethod, DemoUser } from '~/types/auth';

const props = defineProps<{
  onLogin: (method: LoginMethod, credentials: Record<string, string>) => Promise<void>;
  identifiedAccount: DemoUser;
}>();

const password = ref('');
const passwordError = ref('');
const loading = ref(false);

async function handleSubmit() {
  if (!password.value) {
    passwordError.value = '请输入密码';
    return;
  }
  if (password.value.length < 6) {
    passwordError.value = '密码长度不能少于 6 位';
    return;
  }
  passwordError.value = '';
  loading.value = true;
  await props.onLogin('password', { username: props.identifiedAccount.username, password: password.value });
  loading.value = false;
}
</script>
